softeerbootcamp-6th/Team3-SockThree

.env.production, .github/workflows/build-and-push.yml, .github/workflows/deploy.yml, .gitignore, deploy.sh, docker-compose.yml, server/Dockerfile, server/src/main/resources/application-dev.yml, server/src/main/resources/application-prod.yml, server/src/main/resources/application.yml
[Closes #61]
---
- 환경별 Profile 생성
- Dockerfile, docker-compose 설정
- workflow 수정
---
- [BE-Deploy](https://github.com/softeerbootcamp-6th/Team3-SockThree/wiki/BE%E2%80%90Deployment)
=>  [FEATURE] - 도커라이징 증 배포 환경 설정

.env.example, .github/workflows/deploy.yml, deploy.sh, docker-compose.yml
[Closes #65]
---
- github tokens 추가
---
-
=> [FIX] - docker compose 배포환경에서 실행 안되는 문제

client/global.css
=> FE 아키텍처 설정

server/src/main/java/com/seniclass/server/domain/lecture/domain/Lecture.java, server/src/main/java/com/seniclass/server/domain/lecture/enums/Level.java, server/src/main/java/com/seniclass/server/domain/lecture/repository/LectureRepository.java
[Closes #88]
---
- 강좌 엔티티 생성
- 강좌 Level enum 생성
- 강좌 Spring Data JPA Repository 생성
- **연관 관계 매핑 제외**
---
-
=>  [FEATURE] - 강좌 도메인 생성

server/src/main/java/com/seniclass/server/domain/lecture/domain/Lecture.java
[Closes #90  ]
---
- name 필드 타입 Integer -> String 으로 수정
---
-
=>  [FIX] - Lecture 엔티티 필드 타입 수정

server/build.gradle, server/src/main/java/com/seniclass/server/ServerApplication.java, server/src/main/java/com/seniclass/server/domain/common/model/BaseTimeEntity.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/Lecture.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/UploadTime.java, server/src/main/java/com/seniclass/server/domain/lecture/enums/Level.java, server/src/main/java/com/seniclass/server/domain/lecture/repository/LectureRepository.java, server/src/main/java/com/seniclass/server/domain/lecture/repository/UploadTimeRepository.java, server/src/main/java/com/seniclass/server/domain/student/enums/Gender.java, server/src/main/java/com/seniclass/server/global/config/swagger/SwaggerConfig.java, server/src/main/java/com/seniclass/server/global/exception/CommonException.java, server/src/main/java/com/seniclass/server/global/exception/ErrorResponse.java, server/src/main/java/com/seniclass/server/global/exception/GlobalExceptionHandler.java, server/src/main/java/com/seniclass/server/global/exception/errorcode/BaseErrorCode.java, server/src/main/java/com/seniclass/server/global/exception/errorcode/GlobalErrorCode.java, server/src/main/java/com/seniclass/server/global/response/CommonResponse.java, server/src/main/java/com/seniclass/server/global/response/CommonResponseAdvice.java, server/src/test/java/com/seniclass/server/ServerApplicationTests.java
[Closes #92 ]
---
- UploadTime 엔티티 생성
- UploadTime 레포지토리 생성
- UploadTime 엔티티와 Lecture 엔티티 연관관계 매핑
---
-
=> [FEATURE] - UploadTime 엔티티 생성 및 연관관계 매핑

server/src/main/java/com/seniclass/server/domain/lecture/repository/LectureRepository.java, server/src/main/java/com/seniclass/server/domain/lecture/repository/UploadTimeRepository.java, server/src/main/java/com/seniclass/server/domain/lecture/repository/WidgetSettingRepository.java
[Closes #102 ]
---
- 강좌 관련 레포지토리 인터페이스에서 Repository 애노테이션 누락된 부분 수정 
- Lecture, UploadTime, WidgetSetting 
---
-
=> [FIX] - Repository 애노테이션 누락 수정

docker-compose.yml
[Closes #122 ]
---
- Docker 컨테이너에 Nginx 추가
- EC2의 SSL 인증서를 통한 HTTPS 통신 설정
---
-
=> [FEATURE] - docker-compose.yml 설정 수정

server/src/main/java/com/seniclass/server/domain/lecture/controller/LectureController.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/Lecture.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/request/LectureCreateRequest.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/request/LectureUpdateRequest.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/LectureResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/repository/LectureRepository.java, server/src/main/java/com/seniclass/server/domain/lecture/service/LectureService.java, server/src/main/java/com/seniclass/server/domain/lecture/service/LectureServiceImpl.java, server/src/main/java/com/seniclass/server/global/exception/errorcode/LectureErrorCode.java
[Closes #125 ]
---
- Lecture 엔티티에 대한 기본 CRUD 를 구현했습니다.
- dto를 통해서 값의 유효성 검사를 최대한 하려고 했습니다.
- 유효성 검사 /로직 처리 중에 발생하는 오류들을 LectureErrorCode 를 통해서 처리하도록 했습니다 
---
-
=> [FEATURE] - Lecture 엔티티 기본 CRUD 구현

server/src/main/java/com/seniclass/server/domain/lecture/domain/Review.java, server/src/main/java/com/seniclass/server/domain/lecture/repository/ReviewRepository.java
[Closes #115 ]
---
- Review 엔티티 생성
- Review 레포지토리 생성
---
-
=> [FEATURE] - 리뷰 엔티티 기본 생성

server/src/main/java/com/seniclass/server/domain/category/domain/MainCategory.java, server/src/main/java/com/seniclass/server/domain/category/domain/SubCategory.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/Assignment.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/Chapter.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/Lecture.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/UploadTime.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/Video.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/WidgetSetting.java, server/src/main/java/com/seniclass/server/domain/student/domain/AssignmentSubmission.java, server/src/main/java/com/seniclass/server/domain/student/domain/InterestingCategory.java, server/src/main/java/com/seniclass/server/domain/student/domain/LectureBookmark.java, server/src/main/java/com/seniclass/server/domain/student/domain/LectureEnrollment.java, server/src/main/java/com/seniclass/server/domain/student/domain/LectureQna.java, server/src/main/java/com/seniclass/server/domain/student/domain/VideoProgress.java
[Closes #146]
---
- Id 에 해당하는 컬럼의 경우 `@Column` 삭제
- 일반 컬럼의 경우 `@Column` 의 name 을 통한 컬럼명 설정 삭제
- MySQL 예약어에 해당하는 컬럼명 수정
---
-
=> [REFACTOR] - JPA 엔티티 컬럼 설정 수정

client/eslint.config.js
[Closes #164]
- 린트에 화살표 함수, import 경로 관련 규칙을 추가했습니다.
- 변경 후에 잘못된 파일이 존재했는데, 지애님이 이미 다른 브랜치에서 수정하셨다고 해서 수정하지 않았습니다! (code quality 통과 못해도 양해해주세요)
=> [CHORE] - FE 공통 컨벤션 린트에 추가

server/src/main/java/com/seniclass/server/domain/lecture/controller/LectureController.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/request/LectureCreateRequest.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/request/LectureUpdateRequest.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/LectureResponse.java
[Closes #167 ]
---
- 강좌 도메인 dto swagger 문서 작업
---
-
=> [CHORE] - swagger 문서 작업

server/src/main/java/com/seniclass/server/domain/lecture/controller/ChapterController.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/Chapter.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/request/ChapterCreateRequest.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/request/ChapterUpdateRequest.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/ChapterResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/exception/errorcode/ChapterErrorCode.java, server/src/main/java/com/seniclass/server/domain/lecture/service/ChapterService.java, server/src/main/java/com/seniclass/server/domain/lecture/service/ChapterServiceImpl.java, server/src/main/java/com/seniclass/server/global/exception/errorcode/UserErrorCode.java
[Closes #190]
---
- Controller , Service 생성
- 과제와 마찬가지로 검증 로직을 포함했습니다
---
-
=> [FEATURE] - 단원 CRUD 구현

.github/workflows/ci.yml, server/build.gradle, server/src/main/java/com/seniclass/server/domain/aws/service/S3Service.java, server/src/main/java/com/seniclass/server/global/config/aws/AwsConfig.java, server/src/main/resources/application-dev.yml, server/src/main/resources/application-prod.yml, server/src/main/resources/application-test.yml, server/src/main/resources/application.yml
[Closes #182]
---
- aws config 생성
- 이미지 CRUD 를 위한 S3 Service 코드 구현
---
-
=> [FEATURE] - S3 Service 코드 구현

.github/workflows/ci.yml, docker-compose.yml, server/src/main/java/com/seniclass/server/domain/aws/service/S3FileStorageService.java, server/src/main/java/com/seniclass/server/domain/aws/service/S3Service.java, server/src/main/java/com/seniclass/server/domain/student/domain/AssignmentSubmission.java, server/src/main/java/com/seniclass/server/domain/student/dto/AssignmentSubmissionResponse.java, server/src/main/java/com/seniclass/server/domain/student/service/AssignmentSubmissionServiceImpl.java, server/src/main/java/com/seniclass/server/global/service/FileStorageService.java, server/src/main/resources/application-dev.yml, server/src/main/resources/application-prod.yml, server/src/main/resources/application-test.yml, server/src/main/resources/application.yml, server/src/test/java/com/seniclass/server/domain/aws/service/S3FileStorageServiceTest.java, server/src/test/java/com/seniclass/server/domain/student/service/AssignmentSubmissionServiceTest.java
[Closes #202 ]
---
- presignedurl 생성 로직 추가
- s3를 이용한 file storage 구현
- application.yml profile 수정
---
-
=> [FEATURE] - 과제 업로드 기능 구현

server/src/main/java/com/seniclass/server/domain/lecture/controller/LectureController.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/LectureBannerResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/service/LectureService.java, server/src/main/java/com/seniclass/server/domain/lecture/service/LectureServiceImpl.java, server/src/main/java/com/seniclass/server/domain/student/repository/LectureBookmarkRepository.java, server/src/main/java/com/seniclass/server/domain/student/repository/LectureEnrollmentRepository.java
[Closes #237]
---
- 강좌 배너 위젯 API 작성
---
-
=> [FEATURE] - 강좌 배너 위젯에 대한 API 생성 

server/src/main/java/com/seniclass/server/global/config/swagger/SwaggerConfig.java
[Closes #257 ]
---
- swagger server url 상대경로로 명시
---
-
=>  [FIX] - Swagger CORS Error

server/src/main/java/com/seniclass/server/domain/lecture/controller/ReviewController.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/Review.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/request/ReviewCreateRequest.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/request/ReviewUpdateRequest.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/ReviewResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/exception/errorcode/ReviewErrorCode.java, server/src/main/java/com/seniclass/server/domain/lecture/repository/ReviewRepository.java, server/src/main/java/com/seniclass/server/domain/lecture/service/ReviewService.java, server/src/main/java/com/seniclass/server/domain/lecture/service/ReviewServiceImpl.java, server/src/main/java/com/seniclass/server/domain/student/controller/AssignmentSubmissionController.java, server/src/main/java/com/seniclass/server/domain/student/dto/request/FeedbackUpdateRequest.java, server/src/main/java/com/seniclass/server/domain/student/service/AssignmentSubmissionService.java, server/src/main/java/com/seniclass/server/domain/student/service/AssignmentSubmissionServiceImpl.java
[Closes #260 ]
---
- 리뷰 도메인 CRUD 개발
- 강사 과제 피드백 업데이트 API 구현
---
-
=>  [FEATURE] - 리뷰 관련 API, 강사의 과제 피드백

server/src/main/java/com/seniclass/server/domain/auth/service/AuthWebConfig.java, server/src/main/java/com/seniclass/server/domain/aws/service/S3Service.java, server/src/main/java/com/seniclass/server/domain/lecture/controller/VideoController.java, server/src/main/java/com/seniclass/server/domain/lecture/domain/Video.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/request/VideoUploadRequest.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/VideoUploadResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/exception/errorcode/VideoErrorCode.java, server/src/main/java/com/seniclass/server/domain/lecture/service/VideoService.java, server/src/main/java/com/seniclass/server/domain/lecture/service/VideoServiceImpl.java
[Closes #263 ]
---
- FE → BE: POST /lectures/{lectureId}/chapters/{chapterId}/video
동영상 정보 전송
Video 엔티티 생성 (streamable=false)
S3 Upload Presigned URL 응답
FE → S3: Presigned URL로 동영상 업로드
- Finalize
Lambda → BE: POST /lectures/{lectureId}/chapters/{chapterId}/video/{videoId}/finalize
Video.streamable = true로 변경
streamingPath 설정
---
-
=> [FEATURE] - 동영상 업로드 요청 및 presigned url 반환 API

server/src/main/java/com/seniclass/server/domain/auth/dto/LoginResponse.java, server/src/main/java/com/seniclass/server/domain/auth/service/AuthService.java
[Closes #273 ]
---
- 사용자 로그인 응답 정보 수정
- accessToken 과 role 만 반환
---
-
=> [FEATURE] - login dto 수정

server/src/main/java/com/seniclass/server/domain/auth/dto/LoginResponse.java, server/src/main/java/com/seniclass/server/domain/auth/dto/RegisterResponse.java, server/src/main/java/com/seniclass/server/domain/auth/dto/TokenResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/AssignmentResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/ChapterResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/LectureBannerResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/LectureInfoWidgetResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/LectureResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/MyLectureStatusWidgetResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/ReviewResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/UploadTimeResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/VideoUploadResponse.java, server/src/main/java/com/seniclass/server/domain/lecture/dto/response/WidgetSettingResponse.java, server/src/main/java/com/seniclass/server/domain/student/dto/response/AssignmentSubmissionResponse.java, server/src/main/java/com/seniclass/server/domain/student/dto/response/InterestingCategoryResponse.java, server/src/main/java/com/seniclass/server/domain/student/dto/response/LectureBookmarkResponse.java, server/src/main/java/com/seniclass/server/domain/student/dto/response/LectureEnrollmentResponse.java, server/src/main/java/com/seniclass/server/domain/student/dto/response/LectureQnaResponse.java, server/src/main/java/com/seniclass/server/domain/student/dto/response/StudentInfoResponse.java, server/src/main/java/com/seniclass/server/domain/student/dto/response/VideoProgressResponse.java, server/src/main/java/com/seniclass/server/domain/widget/dto/response/AssignmentWidgetResponse.java, server/src/main/java/com/seniclass/server/domain/widget/dto/response/LectureStatisticsResponse.java, server/src/main/java/com/seniclass/server/domain/widget/dto/response/QnaWidgetResponse.java, server/src/main/java/com/seniclass/server/domain/widget/dto/response/ReviewWidgetResponse.java, server/src/main/java/com/seniclass/server/domain/widget/dto/response/TeacherWidgetResponse.java, server/src/main/java/com/seniclass/server/global/exception/ErrorResponse.java, server/src/main/java/com/seniclass/server/global/response/CommonResponse.java
[Closes #286]
---
- 타입 스크립트 최적화를 위해 dto 문서 수정
---
-
=> [CHORE] - swagger 문서 수정

client/src/domain/instructor/api/lectures.ts, client/src/domain/student/api/bookmarks.ts, client/src/domain/student/api/reviews.ts, client/src/shared/api/core/createApi.ts, client/src/shared/api/core/http.ts, client/src/shared/api/lectures.ts, client/src/shared/api/reviews.ts, client/src/shared/types/openapi.ts
[Closes #285]
- API 함수를 정의했습니다.
- 쿼리키는.. 다시 맞춰나가는게 좋을 것 같습니다. 여러 방법을 리서치해올게요. ㅎㅎ
현재 북마크 삭제 api가 2개로 나뉘어있습니다.
```ts
// 북마크 삭제
const removeBookmarkByBookmarkId = (bookmarkId: number) =>
bookmarksApi.del<void>(`/${bookmarkId}`);
const removeBookmarkByLectureId = (lectureId: number) =>
bookmarksApi.del<void>(`/lecture/${lectureId}`);
```
훅은 하나로 통일하는 것이 좋을 것 같아, 다음과 같이 구성했습니다.
```ts
/**
* 사용법
* useRemoveBookmark()({ bookmarkId: 1 });
* useRemoveBookmark()({ lectureId: 1 });
* bookmarkId 또는 lectureId 중 하나는 필수입니다. 명시적으로 작성해주세요
*/
export const useRemoveBookmark = () => {
const queryClient = useQueryClient();
return useMutation({
mutationFn: ({
bookmarkId,
lectureId,
}: {
bookmarkId?: number;
lectureId?: number;
}) => {
if (bookmarkId) {
return removeBookmarkByBookmarkId(bookmarkId);
} else if …
```
=> [FEATURE] - Review, Lecture, Widget, Bookmark API 함수 정의
